import React, { useEffect, useState } from 'react';
import { ArrowRight, Bell, Search, Users } from 'lucide-react';
import { date } from './api.js';
import { loadStudents, loadStudent, saveCourse, sendStudentNotification } from './cloudData.js';
import './admin.css';

export default function AdminStudents() {
 const [students,setStudents]=useState([]),[selected,setSelected]=useState(null),[course,setCourse]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async()=>setStudents(await loadStudents());
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 async function open(student){setError('');setNotice('');try{const result=await loadStudent(student.id);setSelected(result);setCourse(result.courseNumber||'');setMessage('');}catch(e){setError(e.message);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await saveCourse(selected.id,course);setSelected(old=>({...old,courseNumber:course.trim()}));await refresh();setNotice('حُفظ رقم الدورة.');}catch(cause){setError(cause.message);}finally{setBusy(false);}}
 async function send(e){e.preventDefault();setBusy(true);setError('');try{await sendStudentNotification(selected.id,message);setMessage('');setNotice('وصل الإشعار إلى حساب الطالب.');}catch(cause){setError(cause.message);}finally{setBusy(false);}}
 const filtered=students.filter(student=>`${student.name} ${student.email} ${student.courseNumber||''}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="admin-students">{error&&<p className="cloud-error" role="alert">{error}</p>}{notice&&<p className="admin-success" role="status">{notice}</p>}{selected?<><button className="back-button" onClick={()=>{setSelected(null);setNotice('');}}><ArrowRight size={18}/> سجل الطلاب</button><section className="section-block"><span className="overline">ملف الطالب</span><h3>{selected.name}</h3><p dir="ltr" className="admin-email">{selected.email}</p><p className="scope-note">تاريخ التسجيل: {date(selected.createdAt)}</p><form className="admin-course-form" onSubmit={save}><label>رقم الدورة<input value={course} maxLength="30" onChange={e=>setCourse(e.target.value)} placeholder="مثال: ١٤٤٨ / الدورة الأولى"/></label><button className="secondary-button" disabled={busy}>حفظ رقم الدورة</button></form><h4>المواد المسجّل بها</h4><p className="scope-note">هذه المواد مأخوذة من القنوات التي انضم إليها الطالب؛ لا تعني أنه أكمل دراستها.</p>{selected.channels.length?<div className="admin-subjects">{selected.channels.map(channel=><div className="admin-subject" key={channel.id}><strong>{channel.subject}</strong><span>{channel.name} · {channel.book}</span></div>)}</div>:<p className="quiet-empty">لم ينضم الطالب إلى أي قناة بعد.</p>}</section><section className="section-block"><div className="section-head"><div><h3>إرسال إشعار خاص</h3><p>يظهر للطالب داخل حسابه فقط.</p></div><Bell size={20}/></div><form className="admin-message-form" onSubmit={send}><label>نص الإشعار<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength="1000" required rows="4" placeholder="مثال: تنبيه بخصوص الحضور في الدورة"/></label><button className="primary-button" disabled={busy||!message.trim()}>إرسال الإشعار</button></form></section></>:<section className="section-block"><div className="section-head"><div><h3>سجل طلاب الحوزة</h3><p>{students.length} حساب طالب مسجّل</p></div><Users size={22}/></div><label className="admin-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو البريد أو الدورة"/></label>{filtered.length?<div className="lecture-stack">{filtered.map(student=><article className="lecture-row" key={student.id}><div className="round-icon mint"><Users size={18}/></div><div className="lecture-main"><strong>{student.name}</strong><span dir="ltr">{student.email}</span><small>الدورة: {student.courseNumber||'غير محددة'} · المواد: {student.subjects?.join('، ')||'لم يسجّل مادة'}</small></div><button className="row-action" onClick={()=>open(student)}>فتح الحساب</button></article>)}</div>:<p className="quiet-empty">لا توجد حسابات تطابق البحث.</p>}</section>}</div>;
}
