import { useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { json } from './api.js';
import './account.css';
export default function CloudAccount({onLogin}) {
 const [mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[inviteCode,setInviteCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{await json('/auth/'+(mode==='register'?'register':'login'),'POST',{name,email,password,inviteCode});await onLogin();}catch(cause){setError(cause.message);}finally{setBusy(false);}}
 return <section className="account-card account-form cloud-auth"><div className="account-medallion"><LockKeyhole size={26}/></div><span className="overline">بوابة المدرسة</span><h2>{mode==='register'?'إنشاء حساب':'تسجيل الدخول'}</h2><p>الطالب ينشئ حسابه، والأستاذ يسجّل ببريده الذي تعتمده الإدارة.</p><div className="account-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('');}}>تسجيل الدخول</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('');}}>إنشاء حساب</button></div><form onSubmit={submit}>{mode==='register'&&<label>الاسم الكامل<input value={name} onChange={e=>setName(e.target.value)} required maxLength="70" autoComplete="name"/></label>}<label>البريد الإلكتروني<input dir="ltr" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>كلمة المرور<input dir="ltr" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='register'?10:1} required autoComplete={mode==='register'?'new-password':'current-password'}/></label>{mode==='register'&&<label>رمز دعوة الأستاذ <small>اتركه فارغًا إذا كنت طالبًا</small><input dir="ltr" value={inviteCode} onChange={e=>setInviteCode(e.target.value)} autoComplete="off"/></label>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'جارٍ التنفيذ…':mode==='register'?'إنشاء الحساب':'دخول'}</button></form><p className="account-notice">الأستاذ يستخدم بريده ورمز الدعوة اللذين تسلّمهما من المدير.</p></section>;
}
